(() => {
  "use strict";

  const DEMO_SESSION_KEY = "hotel-lumiere-demo-session";
  const REQUEST_TIMEOUT_MS = 30_000;

  const dom = {
    form: document.querySelector("#simulationForm"),
    guestName: document.querySelector("#guestName"),
    language: document.querySelector("#guestLanguage"),
    scenario: document.querySelector("#scenario"),
    isDemo: document.querySelector("#isDemo"),
    chatMessages: document.querySelector("#chatMessages"),
    messageForm: document.querySelector("#messageForm"),
    messageInput: document.querySelector("#messageInput"),
    sendButton: document.querySelector("#sendButton"),
    transcript: document.querySelector("#transcript"),
    inboxName: document.querySelector("#inboxGuestName"),
    inboxContext: document.querySelector("#inboxGuestContext"),
    initials: document.querySelector("#guestInitials"),
    handoffButton: document.querySelector("#handoffButton"),
    handoffStatus: document.querySelector("#handoffStatus"),
    handoffTitle: document.querySelector("#handoff-title"),
    handoffDescription: document.querySelector("#handoffDescription"),
    conversationMode: document.querySelector("#conversationMode"),
    staffAlert: document.querySelector("#staffAlert"),
    staffAlertTitle: document.querySelector("#staffAlertTitle"),
    staffAlertBody: document.querySelector("#staffAlertBody"),
    sheet: document.querySelector("#serviceSheet"),
    backdrop: document.querySelector("#sheetBackdrop"),
    closeSheet: document.querySelector("#closeSheet")
  };

  let session = null;
  let humanHandoff = false;
  let lastFocusedElement = null;
  let activeController = null;

  function timeNow() {
    return new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(new Date());
  }

  function getDemoSessionId() {
    try {
      const existing = window.sessionStorage.getItem(DEMO_SESSION_KEY);
      if (existing && /^demo_[A-Za-z0-9_-]+$/.test(existing)) return existing;
      const created = `demo_${crypto.randomUUID()}`;
      window.sessionStorage.setItem(DEMO_SESSION_KEY, created);
      return created;
    } catch {
      return `demo_${crypto.randomUUID()}`;
    }
  }

  function configuredDemoEndpoint() {
    const explicit = String(window.CONCIERGE_DEMO_ENDPOINT || "").trim();
    if (explicit) return explicit;
    const chatEndpoint = String(window.CONCIERGE_WEBHOOK_URL || "").trim();
    return chatEndpoint.replace(/\/api\/chat(?:\?.*)?$/i, "/api/demo-chat");
  }

  function initialsFor(name) {
    return name.trim().split(/\s+/).slice(0, 2).map((part) => part.charAt(0).toUpperCase()).join("") || "G";
  }

  function scenarioLabel() {
    return dom.scenario.options[dom.scenario.selectedIndex].text;
  }

  function clearChildren(element) {
    element.replaceChildren();
  }

  function addTranscript(actor, text, type) {
    const item = document.createElement("li");
    item.className = `transcript-entry transcript-entry--${type}`;
    const meta = document.createElement("div");
    meta.className = "transcript-meta";
    meta.textContent = `${timeNow()} · ${actor}`;
    const body = document.createElement("div");
    body.className = "transcript-text";
    body.textContent = text;
    item.append(meta, body);
    dom.transcript.append(item);
    dom.transcript.scrollTop = dom.transcript.scrollHeight;
  }

  function buildActionButton(label, className, action) {
    const button = document.createElement("button");
    button.type = "button";
    button.className = className;
    button.textContent = label;
    button.dataset.action = action;
    return button;
  }

  function addMessage({ sender, text, quickReplies = [], listMessage = false }) {
    const message = document.createElement("article");
    message.className = `message message--${sender}`;
    const body = document.createElement("p");
    body.textContent = text;
    message.append(body);

    if (sender === "ai" && (quickReplies.length || listMessage)) {
      const actions = document.createElement("div");
      actions.className = "message-actions";
      quickReplies.slice(0, 3).forEach((reply) => actions.append(buildActionButton(reply, "quick-reply", "quick-reply")));
      if (listMessage) actions.append(buildActionButton("View Services", "list-message", "view-services"));
      message.append(actions);
    }

    const meta = document.createElement("div");
    meta.className = "message-meta";
    meta.textContent = timeNow();
    message.append(meta);
    dom.chatMessages.append(message);
    dom.chatMessages.scrollTop = dom.chatMessages.scrollHeight;
    addTranscript(sender === "guest" ? "Guest" : "AI Concierge", text, sender === "guest" ? "guest" : "ai");
  }

  function addChatChrome() {
    const date = document.createElement("p");
    date.className = "chat-date";
    date.textContent = "Today";
    const notice = document.createElement("p");
    notice.className = "chat-encryption";
    notice.textContent = "Demo session · replies are generated by the concierge service.";
    dom.chatMessages.append(date, notice);
  }

  function addTypingIndicator() {
    const indicator = document.createElement("div");
    indicator.className = "typing-indicator";
    indicator.setAttribute("aria-label", "AI Concierge is typing");
    indicator.append(document.createElement("span"), document.createElement("span"), document.createElement("span"));
    dom.chatMessages.append(indicator);
    dom.chatMessages.scrollTop = dom.chatMessages.scrollHeight;
    return indicator;
  }

  function setBusy(isBusy) {
    dom.messageInput.disabled = isBusy;
    dom.sendButton.disabled = isBusy;
  }

  function setOwnerStatus({ human }) {
    dom.handoffStatus.replaceChildren();
    const dot = document.createElement("span");
    dot.className = "status-dot";
    dot.setAttribute("aria-hidden", "true");
    dom.handoffStatus.append(dot, human ? " Human active" : " Active");
  }

  function updateGuestSummary() {
    dom.inboxName.textContent = session.name;
    dom.inboxContext.textContent = `${session.language} · ${scenarioLabel()}`;
    dom.initials.textContent = initialsFor(session.name);
  }

  function resetHandoff() {
    humanHandoff = false;
    dom.handoffButton.classList.remove("is-human");
    dom.handoffButton.textContent = "Take over chat";
    dom.handoffButton.setAttribute("aria-pressed", "false");
    dom.handoffStatus.classList.remove("is-human");
    setOwnerStatus({ human: false });
    dom.handoffTitle.textContent = "AI Concierge";
    dom.handoffDescription.textContent = "AI replies are enabled for this simulation.";
    dom.conversationMode.classList.remove("is-human");
    dom.conversationMode.textContent = "AI active";
  }

  function hideStaffAlert() {
    dom.staffAlert.hidden = true;
    dom.staffAlertTitle.textContent = "Reception follow-up";
    dom.staffAlertBody.textContent = "";
  }

  function renderStaffAlerts(alerts) {
    if (!Array.isArray(alerts) || !alerts.length) return;
    const alert = alerts[0];
    dom.staffAlert.hidden = false;
    dom.staffAlertTitle.textContent = `${alert.role || "Reception"} notified`;
    dom.staffAlertBody.textContent = alert.summary || "A concierge request was created for team follow-up.";
    addTranscript("Staff alert", `${alert.role || "Reception"}: ${alert.summary || "New concierge request."}`, "human");
  }

  function launchSimulation() {
    activeController?.abort();
    activeController = null;
    session = {
      id: getDemoSessionId(),
      name: dom.guestName.value.trim() || "Guest",
      language: dom.language.value,
      scenario: dom.scenario.value,
      isDemo: dom.isDemo.value === "true",
      chatHistory: []
    };
    resetHandoff();
    hideStaffAlert();
    updateGuestSummary();
    clearChildren(dom.chatMessages);
    clearChildren(dom.transcript);
    addChatChrome();
    addTranscript("System", `Demo session launched for ${session.name}. Airtable isolation is enabled.`, "ai");
    setBusy(false);
  }

  function disableMessageActions(button) {
    button.closest(".message-actions")?.querySelectorAll("button").forEach((actionButton) => { actionButton.disabled = true; });
  }

  function partnerQuickReplies(result) {
    return (Array.isArray(result.partner_offers) ? result.partner_offers : [])
      .map((offer) => String(offer?.name || "").trim())
      .filter(Boolean)
      .slice(0, 3);
  }

  async function requestConciergeReply() {
    const endpoint = configuredDemoEndpoint();
    if (!endpoint) throw new Error("The demo chat endpoint is not configured.");
    const typing = addTypingIndicator();
    const controller = new AbortController();
    activeController = controller;
    setBusy(true);
    const timeout = window.setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          guestName: session.name,
          language: session.language,
          scenario: session.scenario,
          is_demo: true,
          sessionId: session.id,
          chatHistory: session.chatHistory.map((item) => ({ role: item.role, content: item.content }))
        })
      });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.error || `The concierge service returned ${response.status}.`);
      const reply = String(result.reply || "").trim();
      if (!reply) throw new Error("The concierge service returned an empty reply.");
      session.chatHistory.push({ role: "assistant", content: reply });
      addMessage({ sender: "ai", text: reply, quickReplies: partnerQuickReplies(result), listMessage: true });
      renderStaffAlerts(result.staff_alerts);
    } finally {
      window.clearTimeout(timeout);
      typing.remove();
      if (activeController === controller) activeController = null;
      setBusy(false);
    }
  }

  async function sendGuestMessage(text) {
    const cleanText = text.trim();
    if (!cleanText || !session || activeController) return;
    addMessage({ sender: "guest", text: cleanText });
    session.chatHistory.push({ role: "user", content: cleanText });
    if (humanHandoff) {
      addTranscript("System", "AI response withheld while a receptionist owns this conversation.", "human");
      return;
    }
    try {
      await requestConciergeReply();
    } catch (error) {
      const message = error instanceof Error && error.name === "AbortError"
        ? "The concierge took too long to respond. Please try again."
        : "The concierge service is unavailable at the moment. Please try again shortly.";
      addMessage({ sender: "ai", text: message });
      addTranscript("System", error instanceof Error ? error.message : "Demo chat request failed.", "human");
    }
  }

  function openServices() {
    lastFocusedElement = document.activeElement;
    dom.backdrop.hidden = false;
    dom.sheet.hidden = false;
    dom.closeSheet.focus();
  }

  function closeServices() {
    dom.sheet.hidden = true;
    dom.backdrop.hidden = true;
    if (lastFocusedElement instanceof HTMLElement) lastFocusedElement.focus();
  }

  function toggleHandoff() {
    humanHandoff = !humanHandoff;
    dom.handoffButton.classList.toggle("is-human", humanHandoff);
    dom.handoffButton.textContent = humanHandoff ? "Resume AI Concierge" : "Take over chat";
    dom.handoffButton.setAttribute("aria-pressed", String(humanHandoff));
    dom.handoffStatus.classList.toggle("is-human", humanHandoff);
    setOwnerStatus({ human: humanHandoff });
    dom.handoffTitle.textContent = humanHandoff ? "Human receptionist" : "AI Concierge";
    dom.handoffDescription.textContent = humanHandoff
      ? "Human Agent Active — AI Paused. New guest messages will not receive automated replies."
      : "AI replies are enabled for this simulation.";
    dom.conversationMode.classList.toggle("is-human", humanHandoff);
    dom.conversationMode.textContent = humanHandoff ? "Human active" : "AI active";
    addTranscript("System", humanHandoff ? "Human receptionist took over the conversation. AI paused." : "AI Concierge resumed.", humanHandoff ? "human" : "ai");
  }

  dom.form.addEventListener("submit", (event) => {
    event.preventDefault();
    launchSimulation();
  });

  dom.messageForm.addEventListener("submit", async (event) => {
    event.preventDefault();
    const text = dom.messageInput.value;
    dom.messageInput.value = "";
    await sendGuestMessage(text);
    if (!dom.messageInput.disabled) dom.messageInput.focus();
  });

  dom.chatMessages.addEventListener("click", (event) => {
    const button = event.target.closest("button[data-action]");
    if (!button || button.disabled) return;
    if (button.dataset.action === "view-services") {
      openServices();
      return;
    }
    if (button.dataset.action === "quick-reply") {
      disableMessageActions(button);
      sendGuestMessage(button.textContent || "");
    }
  });

  document.querySelectorAll(".service-option").forEach((option) => {
    option.addEventListener("click", () => {
      closeServices();
      sendGuestMessage(`I would like to book ${option.dataset.service}.`);
    });
  });

  dom.handoffButton.addEventListener("click", toggleHandoff);
  dom.closeSheet.addEventListener("click", closeServices);
  dom.backdrop.addEventListener("click", closeServices);
  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && !dom.sheet.hidden) closeServices();
  });

  launchSimulation();
})();
